// List of common Tailwind classes for autocomplete
export const TAILWIND_CLASSES = [
  'block', 'inline-block', 'flex', 'inline-flex', 'grid', 'inline-grid',
  'hidden', 'absolute', 'relative', 'fixed', 'sticky',
  'z-0', 'z-10', 'z-20', 'z-30', 'z-40', 'z-50', 'z-auto',
  'container', 'box-border', 'box-content',
  'float-left', 'float-right', 'float-none', 'clear-left', 'clear-right', 'clear-both', 'clear-none',
  'overflow-auto', 'overflow-hidden', 'overflow-visible', 'overflow-scroll',
  'static', 'relative', 'absolute', 'fixed', 'sticky',
  'top-0', 'right-0', 'bottom-0', 'left-0',
  'inset-0', 'inset-x-0', 'inset-y-0',
  'w-full', 'w-screen', 'w-auto', 'w-1/2', 'w-1/3', 'w-2/3', 'w-1/4', 'w-3/4',
  'h-full', 'h-screen', 'h-auto', 'h-1/2',
  'min-h-0', 'min-h-full', 'min-h-screen',
  'max-h-full', 'max-h-screen',
  'min-w-0', 'min-w-full', 'max-w-full', 'max-w-screen-sm', 'max-w-md', 'max-w-lg', 'max-w-xl', 'max-w-2xl', 'max-w-3xl', 'max-w-4xl', 'max-w-5xl', 'max-w-6xl', 'max-w-7xl',
  'p-0', 'p-1', 'p-2', 'p-3', 'p-4', 'p-5', 'p-6', 'p-8', 'p-10', 'p-12', 'p-16', 'p-20', 'p-24',
  'px-0', 'px-1', 'px-2', 'px-3', 'px-4', 'px-5', 'px-6', 'px-8', 'px-10', 'px-12', 'px-16', 'px-20', 'px-24',
  'py-0', 'py-1', 'py-2', 'py-3', 'py-4', 'py-5', 'py-6', 'py-8', 'py-10', 'py-12', 'py-16', 'py-20', 'py-24',
  'pt-0', 'pr-0', 'pb-0', 'pl-0',
  'm-0', 'm-1', 'm-2', 'm-3', 'm-4', 'm-5', 'm-6', 'm-8', 'm-10', 'm-12', 'm-16', 'm-20', 'm-24', 'mx-auto',
  'mx-0', 'my-0', 'mt-0', 'mr-0', 'mb-0', 'ml-0',
  'space-x-0', 'space-x-1', 'space-x-2', 'space-x-3', 'space-x-4', 'space-x-5', 'space-x-6', 'space-x-8', 'space-x-10', 'space-x-12', 'space-x-16', 'space-x-20', 'space-x-24',
  'space-y-0', 'space-y-1', 'space-y-2', 'space-y-3', 'space-y-4', 'space-y-5', 'space-y-6', 'space-y-8', 'space-y-10', 'space-y-12', 'space-y-16', 'space-y-20', 'space-y-24',
  'flex-row', 'flex-col', 'flex-wrap', 'flex-nowrap', 'flex-row-reverse', 'flex-col-reverse',
  'items-start', 'items-end', 'items-center', 'items-baseline', 'items-stretch',
  'justify-start', 'justify-end', 'justify-center', 'justify-between', 'justify-around', 'justify-evenly',
  'self-auto', 'self-start', 'self-end', 'self-center', 'self-stretch',
  'flex-1', 'flex-auto', 'flex-initial', 'flex-none',
  'grid-cols-1', 'grid-cols-2', 'grid-cols-3', 'grid-cols-4', 'grid-cols-5', 'grid-cols-6',
  'gap-0', 'gap-1', 'gap-2', 'gap-3', 'gap-4', 'gap-5', 'gap-6', 'gap-8',
  'col-auto', 'col-span-1', 'col-span-2', 'col-span-3', 'col-span-4', 'col-span-full',
  'row-auto', 'row-span-1', 'row-span-2', 'row-span-3', 'row-span-full',
  'font-sans', 'font-serif', 'font-mono',
  'text-xs', 'text-sm', 'text-base', 'text-lg', 'text-xl', 'text-2xl', 'text-3xl', 'text-4xl', 'text-5xl', 'text-6xl', 'text-7xl', 'text-8xl', 'text-9xl',
  'text-left', 'text-center', 'text-right', 'text-justify',
  'italic', 'not-italic',
  'font-thin', 'font-extralight', 'font-light', 'font-normal', 'font-medium', 'font-semibold', 'font-bold', 'font-extrabold', 'font-black',
  'leading-none', 'leading-tight', 'leading-snug', 'leading-normal', 'leading-relaxed', 'leading-loose',
  'tracking-tighter', 'tracking-tight', 'tracking-normal', 'tracking-wide', 'tracking-wider', 'tracking-widest',
  'underline', 'no-underline', 'line-through',
  'truncate', 'overflow-ellipsis', 'text-clip',
  'uppercase', 'lowercase', 'capitalize', 'normal-case',
  'whitespace-normal', 'whitespace-nowrap', 'whitespace-pre', 'whitespace-pre-line', 'whitespace-pre-wrap',
  'break-normal', 'break-words', 'break-all',
  'bg-transparent', 'bg-current', 'bg-black', 'bg-white', 'bg-gray-100', 'bg-gray-200', 'bg-gray-300', 'bg-gray-400', 'bg-gray-500', 'bg-gray-600', 'bg-gray-700', 'bg-gray-800', 'bg-gray-900',
  'bg-red-100', 'bg-red-200', 'bg-red-300', 'bg-red-400', 'bg-red-500', 'bg-red-600', 'bg-red-700', 'bg-red-800', 'bg-red-900',
  'bg-blue-100', 'bg-blue-200', 'bg-blue-300', 'bg-blue-400', 'bg-blue-500', 'bg-blue-600', 'bg-blue-700', 'bg-blue-800', 'bg-blue-900',
  'bg-green-100', 'bg-green-200', 'bg-green-300', 'bg-green-400', 'bg-green-500', 'bg-green-600', 'bg-green-700', 'bg-green-800', 'bg-green-900',
  'bg-yellow-100', 'bg-yellow-200', 'bg-yellow-300', 'bg-yellow-400', 'bg-yellow-500', 'bg-yellow-600', 'bg-yellow-700', 'bg-yellow-800', 'bg-yellow-900',
  'bg-purple-100', 'bg-purple-200', 'bg-purple-300', 'bg-purple-400', 'bg-purple-500', 'bg-purple-600', 'bg-purple-700', 'bg-purple-800', 'bg-purple-900',
  'bg-pink-100', 'bg-pink-200', 'bg-pink-300', 'bg-pink-400', 'bg-pink-500', 'bg-pink-600', 'bg-pink-700', 'bg-pink-800', 'bg-pink-900',
  'bg-origin-border', 'bg-origin-padding', 'bg-origin-content',
  'bg-bottom', 'bg-center', 'bg-left', 'bg-left-bottom', 'bg-left-top', 'bg-right', 'bg-right-bottom', 'bg-right-top', 'bg-top',
  'bg-repeat', 'bg-no-repeat', 'bg-repeat-x', 'bg-repeat-y', 'bg-round', 'bg-space',
  'bg-auto', 'bg-cover', 'bg-contain',
  'bg-fixed', 'bg-local', 'bg-scroll',
  'bg-gradient-to-t', 'bg-gradient-to-tr', 'bg-gradient-to-r', 'bg-gradient-to-br', 'bg-gradient-to-b', 'bg-gradient-to-bl', 'bg-gradient-to-l', 'bg-gradient-to-tl',
  'border', 'border-0', 'border-2', 'border-4', 'border-8',
  'border-t', 'border-r', 'border-b', 'border-l',
  'border-transparent', 'border-current', 'border-black', 'border-white', 'border-gray-100', 'border-gray-200', 'border-gray-300', 'border-gray-400', 'border-gray-500', 'border-gray-600', 'border-gray-700', 'border-gray-800', 'border-gray-900',
  'rounded-none', 'rounded-sm', 'rounded', 'rounded-md', 'rounded-lg', 'rounded-xl', 'rounded-2xl', 'rounded-3xl', 'rounded-full',
  'rounded-t-none', 'rounded-r-none', 'rounded-b-none', 'rounded-l-none',
  'rounded-tl-none', 'rounded-tr-none', 'rounded-br-none', 'rounded-bl-none',
  'border-solid', 'border-dashed', 'border-dotted', 'border-double', 'border-hidden', 'border-none',
  'shadow-sm', 'shadow', 'shadow-md', 'shadow-lg', 'shadow-xl', 'shadow-2xl', 'shadow-inner', 'shadow-none',
  'opacity-0', 'opacity-5', 'opacity-10', 'opacity-20', 'opacity-25', 'opacity-30', 'opacity-40', 'opacity-50', 'opacity-60', 'opacity-70', 'opacity-75', 'opacity-80', 'opacity-90', 'opacity-95', 'opacity-100',
  'ring-0', 'ring-1', 'ring-2', 'ring-4', 'ring-8', 'ring-inset',
  'ring-transparent', 'ring-current', 'ring-black', 'ring-white', 'ring-gray-100', 'ring-blue-500',
  'cursor-auto', 'cursor-default', 'cursor-pointer', 'cursor-wait', 'cursor-text', 'cursor-move', 'cursor-help', 'cursor-not-allowed',
  'pointer-events-none', 'pointer-events-auto',
  'select-none', 'select-text', 'select-all', 'select-auto',
  'resize-none', 'resize-y', 'resize-x', 'resize',
  'outline-none', 'outline-white', 'outline-black',
  'appearance-none',
  'min-w-0', 'min-w-full', 'max-w-full',
  'min-h-0', 'min-h-full', 'min-h-screen',
  'max-h-full', 'max-h-screen',
  'gap-x-0', 'gap-x-1', 'gap-x-2', 'gap-x-3', 'gap-x-4', 'gap-x-5', 'gap-x-6', 'gap-x-8', 'gap-x-10', 'gap-x-12', 'gap-x-16', 'gap-x-20', 'gap-x-24',
  'gap-y-0', 'gap-y-1', 'gap-y-2', 'gap-y-3', 'gap-y-4', 'gap-y-5', 'gap-y-6', 'gap-y-8', 'gap-y-10', 'gap-y-12', 'gap-y-16', 'gap-y-20', 'gap-y-24',
  'transition-all', 'transition', 'transition-colors', 'transition-opacity', 'transition-shadow', 'transition-transform',
  'duration-75', 'duration-100', 'duration-150', 'duration-200', 'duration-300', 'duration-500', 'duration-700', 'duration-1000',
  'ease-linear', 'ease-in', 'ease-out', 'ease-in-out',
  'scale-0', 'scale-50', 'scale-75', 'scale-90', 'scale-95', 'scale-100', 'scale-105', 'scale-110', 'scale-125', 'scale-150',
  'rotate-0', 'rotate-1', 'rotate-2', 'rotate-3', 'rotate-6', 'rotate-12', 'rotate-45', 'rotate-90', 'rotate-180',
  'translate-x-0', 'translate-y-0', 'translate-x-full', 'translate-y-full',
  'skew-x-0', 'skew-y-0', 'skew-x-1', 'skew-y-1',
  'transform-gpu', 'transform-none', 'transform',
  'filter', 'filter-none',
  'blur-none', 'blur-sm', 'blur', 'blur-md', 'blur-lg', 'blur-xl', 'blur-2xl', 'blur-3xl',
  'brightness-0', 'brightness-50', 'brightness-75', 'brightness-90', 'brightness-95', 'brightness-100', 'brightness-105', 'brightness-110', 'brightness-125', 'brightness-150', 'brightness-200',
  'contrast-0', 'contrast-50', 'contrast-75', 'contrast-100', 'contrast-125', 'contrast-150', 'contrast-200',
  'drop-shadow', 'drop-shadow-sm', 'drop-shadow-md', 'drop-shadow-lg', 'drop-shadow-xl', 'drop-shadow-2xl', 'drop-shadow-none',
  'grayscale', 'grayscale-0',
  'hue-rotate-0', 'hue-rotate-15', 'hue-rotate-30', 'hue-rotate-60', 'hue-rotate-90', 'hue-rotate-180',
  'invert', 'invert-0',
  'saturate-0', 'saturate-50', 'saturate-100', 'saturate-150', 'saturate-200',
  'sepia', 'sepia-0',
  'backdrop-filter', 'backdrop-filter-none',
  'backdrop-blur', 'backdrop-brightness', 'backdrop-contrast', 'backdrop-grayscale', 'backdrop-hue-rotate', 'backdrop-invert', 'backdrop-opacity', 'backdrop-saturate', 'backdrop-sepia',
  'content-start', 'content-end', 'content-center', 'content-between', 'content-around', 'content-evenly',
  'place-content-start', 'place-content-end', 'place-content-center', 'place-content-between', 'place-content-around', 'place-content-evenly', 'place-content-stretch',
  'place-items-auto', 'place-items-start', 'place-items-end', 'place-items-center', 'place-items-stretch',
  'place-self-auto', 'place-self-start', 'place-self-end', 'place-self-center', 'place-self-stretch',
  'visible', 'invisible',
  'sr-only', 'not-sr-only',
  'outline-none', 'outline-white', 'outline-black', 'outline-offset-0', 'outline-offset-1', 'outline-offset-2', 'outline-offset-4', 'outline-offset-8',
  'resize-none', 'resize-y', 'resize-x', 'resize',
  'appearance-none',
  'border-collapse', 'border-separate',
  'table-auto', 'table-fixed',
  'caption-top', 'caption-bottom',
  'empty-cells-show', 'empty-cells-hide',
  'list-none', 'list-disc', 'list-decimal',
  'list-inside', 'list-outside',
  'columns-1', 'columns-2', 'columns-3', 'columns-4', 'columns-5', 'columns-6', 'columns-7', 'columns-8', 'columns-9', 'columns-10', 'columns-11', 'columns-12',
  'columns-auto', 'columns-3xs', 'columns-2xs', 'columns-xs', 'columns-sm', 'columns-md', 'columns-lg', 'columns-xl', 'columns-2xl', 'columns-3xl', 'columns-4xl', 'columns-5xl', 'columns-6xl', 'columns-7xl',
  'break-after-auto', 'break-after-avoid', 'break-after-all', 'break-after-avoid-page', 'break-after-page', 'break-after-left', 'break-after-right', 'break-after-column',
  'break-before-auto', 'break-before-avoid', 'break-before-all', 'break-before-avoid-page', 'break-before-page', 'break-before-left', 'break-before-right', 'break-before-column',
  'break-inside-auto', 'break-inside-avoid', 'break-inside-avoid-page', 'break-inside-avoid-column',
  'scroll-auto', 'scroll-smooth',
  'snap-none', 'snap-x', 'snap-y', 'snap-both',
  'snap-mandatory', 'snap-proximity',
  'snap-start', 'snap-end', 'snap-center', 'snap-align-none',
  'scroll-p-0', 'scroll-p-1', 'scroll-p-2', 'scroll-p-3', 'scroll-p-4', 'scroll-p-5', 'scroll-p-6', 'scroll-p-8', 'scroll-p-10', 'scroll-p-12', 'scroll-p-16', 'scroll-p-20', 'scroll-p-24',
  'scroll-px-0', 'scroll-px-1', 'scroll-px-2', 'scroll-px-3', 'scroll-px-4', 'scroll-px-5', 'scroll-px-6', 'scroll-px-8', 'scroll-px-10', 'scroll-px-12', 'scroll-px-16', 'scroll-px-20', 'scroll-px-24',
  'scroll-py-0', 'scroll-py-1', 'scroll-py-2', 'scroll-py-3', 'scroll-py-4', 'scroll-py-5', 'scroll-py-6', 'scroll-py-8', 'scroll-py-10', 'scroll-py-12', 'scroll-py-16', 'scroll-py-20', 'scroll-py-24',
  'scroll-pt-0', 'scroll-pr-0', 'scroll-pb-0', 'scroll-pl-0',
  'scroll-m-0', 'scroll-m-1', 'scroll-m-2', 'scroll-m-3', 'scroll-m-4', 'scroll-m-5', 'scroll-m-6', 'scroll-m-8', 'scroll-m-10', 'scroll-m-12', 'scroll-m-16', 'scroll-m-20', 'scroll-m-24',
  'scroll-mx-0', 'scroll-my-0', 'scroll-mt-0', 'scroll-mr-0', 'scroll-mb-0', 'scroll-ml-0',
  'aspect-auto', 'aspect-square', 'aspect-video',
  '@[0_0_0]', '@[0_0_0]/sm', '@[0_0_0]/md',
];